-------------------------------------------------------------------------------
Test set: com.py.MapperTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 3.262 s <<< FAILURE! - in com.py.MapperTest
testSelectPermsByUserId  Time elapsed: 1.168 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in file [C:\Users\。\Desktop\SpringSecurity\源码\SanGeng_Security_Project_Right\SanGeng_Security_Project\Short_Video_App\target\classes\mapper\MenuMapper.xml]
### The error may involve com.py.mapper.MenuMapper.selectPermsByUserId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in file [C:\Users\。\Desktop\SpringSecurity\源码\SanGeng_Security_Project_Right\SanGeng_Security_Project\Short_Video_App\target\classes\mapper\MenuMapper.xml]
### The error may involve com.py.mapper.MenuMapper.selectPermsByUserId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: 
Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)
Caused by: java.net.UnknownHostException: 不知道这样的主机。 (rm-cn-5yd3h85ce000mpro.rwlb.rds.aliyuncs.com)
	at com.py.MapperTest.testSelectPermsByUserId(MapperTest.java:50)

testGetUserInfoByVideoId  Time elapsed: 1.017 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in file [C:\Users\。\Desktop\SpringSecurity\源码\SanGeng_Security_Project_Right\SanGeng_Security_Project\Short_Video_App\target\classes\mapper\VideoMapper.xml]
### The error may involve com.py.mapper.VideoMapper.getUserIdByVideoId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in file [C:\Users\。\Desktop\SpringSecurity\源码\SanGeng_Security_Project_Right\SanGeng_Security_Project\Short_Video_App\target\classes\mapper\VideoMapper.xml]
### The error may involve com.py.mapper.VideoMapper.getUserIdByVideoId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: 
Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)
Caused by: java.net.UnknownHostException: rm-cn-5yd3h85ce000mpro.rwlb.rds.aliyuncs.com
	at com.py.MapperTest.testGetUserInfoByVideoId(MapperTest.java:45)

testUserMapper  Time elapsed: 1.012 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/py/mapper/UserMapper.java (best guess)
### The error may involve com.py.mapper.UserMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in com/py/mapper/UserMapper.java (best guess)
### The error may involve com.py.mapper.UserMapper.selectList
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: 
Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)
Caused by: java.net.UnknownHostException: rm-cn-5yd3h85ce000mpro.rwlb.rds.aliyuncs.com
	at com.py.MapperTest.testUserMapper(MapperTest.java:57)

